server:
  port: 9292
  servlet:
    context-path: /chat
spring:
  application:
    name: deepseek-ollama
    description: deepseek-ollama 是一个结合了 Spring AI 和 Ollama 的项目，完成调用本地部署的 deepseek 模型的功能。
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com/linyi/controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
# 配置ai
ai:
  ollama:
    url: http://localhost:11434 #这里是我本地部署的ollama默认地址（需要根据你自己的更换）
    chat:
      options:
        model: deepseek-r1:14b # 模型名称 本地ollama 下载的模型名称（需要根据你自己的更换）